name: CheckBuildOnPR

on:

  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run : yarn install
      - run : yarn build
      # - run : yarn test ## LATER IF WE HAVE UNIT TEST IMPLEMENTED
      # - run : yarn start:dev
