name: Deploy_Trial_App_Backend

on:

  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run : yarn install
      - run : yarn build
      # - run : yarn start:dev

  deploy:

    needs : build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "trialprojectbackend"
          heroku_email: "bakerathierry@gmail.com"
